basePath: /
definitions:
  controllers.CommonResponseDTO:
    properties:
      message:
        type: string
    type: object
  controllers.ErrorResponseDTO:
    properties:
      code:
        type: string
      error:
        type: string
      kind:
        type: string
    type: object
  controllers.LoginResponeDTO:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/dto.UserDTO'
    type: object
  controllers.RefreshTokensResponeDTO:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  dto.ConfigDTO:
    properties:
      accessTokenTTLsec:
        type: integer
      refreshTokenTTLsec:
        type: integer
    type: object
  dto.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.RegisterDTO:
    properties:
      email:
        type: string
      password:
        type: string
      password2:
        type: string
    required:
    - email
    - password
    - password2
    type: object
  dto.SessionDTO:
    properties:
      createdAt:
        type: string
      ip:
        type: string
      userAgent:
        type: string
    type: object
  dto.SessionsDTO:
    properties:
      sessions:
        items:
          $ref: '#/definitions/dto.SessionDTO'
        type: array
    type: object
  dto.UserDTO:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: marsel.ave@gmail.com
    name: Marsel Abazbekov
    url: https://github.com/GravityTwoG
  description: Go JWT Auth API example
  title: Go JWT Auth API
  version: "1.0"
paths:
  /auth/active-sessions:
    get:
      description: Get active sessions (list of refresh tokens)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SessionsDTO'
      security:
      - ApiKeyAuth: []
      summary: Get active sessions
      tags:
      - Auth
  /auth/config:
    get:
      description: Get TTL of tokens
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ConfigDTO'
      summary: Get tokens config
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user, also sets refresh token in cookie
      parameters:
      - description: LoginDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LoginResponeDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrorResponseDTO'
      summary: Login user
      tags:
      - Auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CommonResponseDTO'
      security:
      - ApiKeyAuth: []
      summary: Logout user
      tags:
      - Auth
  /auth/logout-all:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CommonResponseDTO'
      security:
      - ApiKeyAuth: []
      summary: Logout all sessions
      tags:
      - Auth
  /auth/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDTO'
      security:
      - ApiKeyAuth: []
      summary: Get current user
      tags:
      - Auth
  /auth/refresh-tokens:
    post:
      description: Refresh tokens, also sets new refresh token in cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RefreshTokensResponeDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrorResponseDTO'
      security:
      - ApiKeyAuth: []
      summary: Refresh tokens
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: RegisterDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponseDTO'
      summary: Register new user
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
